# This docker-compose file is only for local development purposes.
version: '3'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - FILE_BUCKET_NAME
    volumes:
      - './init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh' # Initialise the bucket.
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  maildev:
    image: maildev/maildev
    ports:
      - '1080:80'
      - '1025:25'

  mockpass:
    build: https://github.com/opengovsg/mockpass.git
    environment:
      - SHOW_LOGIN_PAGE=true
    ports:
      - '5156:5156'

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD

